info:
  name: ${project.artifactId}
  version: ${project.version}
  origin: ${scm.url}
  commit: ${buildNumber}
  branch: ${scmBranch}
  built: ${timestamp}

# logging config here as a reminder as to how to override logback from cmd line
# ie -Dlogging.level.org.springframework=DEBUG
logging:
  level:
    org.springframework: WARN
    uk.gov.ons.ctp: DEBUG
    io.pivotal.springcloud: DEBUG

  profile: DEV

liquibase:
  user: samplesvc
  password: samplesvc
  default-schema: sample
  url: jdbc:postgresql://localhost:6432/postgres
  changeLog: classpath:/database/changelog-master.yml

security:
  basic:
    enabled: false
    realm: onsctpiac
  user:
    name: admin
    password: secret

management:
  security:
    roles: SUPERUSER
    enabled: false

server:
  port: 8125
  servlet-path: /

endpoints:
  autoconfig:
    enabled: true
    sensitive: true
  beans:
    enabled: true
    sensitive: true
  configprops:
    enabled: true
    sensitive: true
  dump:
    enabled: true
    sensitive: true
  env:
    enabled: true
    sensitive: true
  info:
    enabled: true
    sensitive: false
  metrics:
    enabled: true
    sensitive: true
  mappings:
    enabled: true
    sensitive: true
  shutdown:
    enabled: true
    sensitive: true
  trace:
    enabled: true
    sensitive: true

spring:
  application:
    name: ONS SampleService


  datasource:
    url: jdbc:postgresql://localhost:6432/postgres
    username: samplesvc
    password: samplesvc
    driverClassName: org.postgresql.Driver
    tomcat:
      initial-size: 5
      max-active: 10
      max-idle: 5
      min-idle: 3

party-svc:
  sample-path: /events
  post-party-path: /party-api/v1/parties
  connection-config:
    scheme: http
    host: ras-party-service-int.apps.devtest.onsclofo.uk
    port: 80
    retry-attempts: 1
    retry-pause-milli-seconds: 5000
    connect-timeout-milli-seconds: 5000
    read-timeout-milli-seconds: 5000 

sftp:
  host: localhost
  port: 122
  username: centos
  password: "JLibV2&XD,"
  directory:
    social: Documents/sftp/social-sftp/
    business: Documents/sftp/business-sftp/
    census: Documents/sftp/census-sftp/
    Documents: Documents/sftp/
  localdirectory: /tmp/samplesvc
  cron: "* * * * * ?"
  filepattern: "*.xml"

rabbitmq:
  username: guest
  password: guest
  host: localhost
  port: 6672
  virtualhost: /
  cron: "* * * * * ?"

redis:
  host: localhost
  port: 7379

data-grid:
  address: localhost:7379
  list-time-to-live-seconds: 600
  list-time-to-wait-seconds: 600
  lock-time-to-live-seconds: 600

messaging:
  backoffInitial: 5000
  backoffMultiplier: 3
  backoffMax: 45000
  consumingThreads: 1
  maxAttempts: 3
  prefetchCount: 10
  txSize: 1
  pubMaxAttempts: 3

sample-unit-distribution:
  retrieval-max: 5672
  distribution-max: 10
  retry-sleep-seconds: 30
  delay-milli-seconds: 60000

swagger-settings:
  swagger-ui-active: true
  group-name: sampleeservice-api
  title: Sample Service API
  description: API for ${project.artifactId}
  version: ${project.version}