liquibase:
  user: postgres
  password: postgres
  url: jdbc:postgresql://localhost:7321/postgres

spring:
  datasource:
    schema: classpath:/schema.sql
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:7321/postgres

sample-unit-distribution:
  delay-milli-seconds: 1000

party-svc:
  connection-config:
    port: 8079

rabbitmq:
  port: 36672

redis:
  port: 8379

data-grid:
  address: localhost:8379