swagger: '2.0'
info:
  title: Sample Service Api
  description: The Sample service manages Survey Samples and forms part of the Response Management product.
    
    Note that all of the endpoints this service provides are authenticated using HTTP basic authentication.
  version: "10.37.0"
schemes:
  - http
basePath: /
produces:
  - application/json
tags:
  - name: Sample
    description: Management of Survey Sample
paths:
  /sampleunitrequests:
    post:
      summary: Creates a CollectionExerciseJob 
      description: Creates a CollectionExerciseJob with the associated collectionExerciseId, surveyRef and exercisedatetime
      consumes:
      - application/json
      parameters:
        - name: Accept
          in: header
          description: Response type, application/json.
          required: false
          type: string
        - name: collectionExerciseJob
          in: body
          description: collectionExerciseJob to be created
          required: true
          schema: 
            $ref: '#/definitions/CollectionExerciseJobCreationRequest'
      tags:
        - Sample
      responses:
        201:
          description: CollectionExerciseJob is created if there are eligible SampleUnits
          schema:
            items:
              $ref: '#/definitions/SampleUnitsRequest'
        400:
          description: CollectionExerciseJob already exists
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  CollectionExerciseJobCreationRequest:
    type: object
    properties:
      surveyref:
        description: Survey Reference
        type: string
      collectionexerciseid:
        description:  Id of Collection Exercise
        type: integer
      exerciseDateTime:
        description:  Effective Survey start dateTime
        type: string
        format: date-time
  Error:
    type: object
    properties:
      code:
        description: Error code
        type: string
      timestamp:
        description:  Unique error timestamp that can be searched for in logs
        type: integer
      message:
        description: Error message
        type: string
  SampleUnitsRequest:
    type: object
    properties:
      sampleUnitsTotal:
        description: Number of SampleUnits eligible for CollectionExerciseJob
        type: integer
securityDefinitions:
  UserSecurity:
    type: basic
security:
  - UserSecurity: [] 